platform :ios, '12.0'
use_frameworks!


workspace 'ProductListMVC'

target 'ProductListMVC' do
  project 'ProductListMVC.xcodeproj'
  pod 'Cosmos', '~> 20.0'
  
  target 'ProductListMVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductListMVCUITests' do
    # Pods for testing
  end

end

