platform :ios, '12.0'
use_frameworks!


workspace 'ProductListMVC'

def layout
  pod 'Cosmos', '~> 20.0'
  pod "KRLCollectionViewGridLayout", "~> 1.0.0"
  pod 'ScrollingContentViewController'
end

target 'ProductListMVC' do
  project 'ProductListMVC.xcodeproj'
  layout
  
  target 'ProductListMVCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProductListMVCUITests' do
    # Pods for testing
  end
end

target 'ProductDetailsMVC' do
  project 'ProductDetailsMVC/ProductDetailsMVC.xcodeproj'
  pod 'ScrollingContentViewController'
  pod 'Cosmos', '~> 20.0'
end

target 'UIComponents' do
  project 'UIComponents/UIComponents.xcodeproj'
  layout

  target 'UIComponentsTests' do
    inherit! :search_paths
    layout
  end
end



